CREATE DATABASE IF NOT EXISTS AIRBNB_DB;
CREATE SCHEMA IF NOT EXISTS AIRBNB;

CREATE TABLE IF NOT EXISTS AIRBNB.AIRBNB_LISTINGS(
    ID INT,
    NAME VARCHAR(500),
    HOST_ID INT,
    HOST_NAME VARCHAR(500),
    NEIGHBOURHOOD_GROUP VARCHAR(50),
    NEIGHBOURHOOD VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ROOM_TYPE VARCHAR(50),
    PRICE INT,
    MINIMUM_NIGHTS INT,
    NUMBER_OF_REVIEWS INT,
    LAST_REVIEW DATE,
    REVIEWS_PER_MONTH FLOAT,
    CALCULATED_HOST_LISTINGS_COUNT INT,
    AVAILABILITY_365 INT
);

CREATE STAGE IF NOT EXISTS AIRBNB_DB.AIRBNB.STAGES;

LIST @AIRBNB_DB.AIRBNB.STAGES;

COPY INTO AIRBNB_DB.AIRBNB.AIRBNB_LISTINGS
FROM @AIRBNB_DB.AIRBNB.STAGES/AB_NYC_2019.csv
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1)
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) FROM AIRBNB_LISTINGS;
SELECT * FROM AIRBNB_LISTINGS LIMIT 10;
SELECT MIN(PRICE), MAX(PRICE), AVG(PRICE) FROM AIRBNB_LISTINGS;
SELECT DISTINCT NEIGHBOURHOOD_GROUP FROM AIRBNB_LISTINGS;